useDotenv: true
variablesResolutionMode: 20210326

service: serverless-skeleton

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage}
  versionFunctions: false
  logRetentionInDays: 1
  deploymentBucket:
    serverSideEncryption: AES256

package:
  individually: true
  exclude:
    - ./**
  include:
    - ./bin/api

functions:
  api:
    handler: bin/api
    memorySize: 512
    timeout: 10
    package:
      include:
        - ./bin/api
    events:
      - http:
          path: /{proxy+}
          method: any
